export default function getCardImage(cardID) {
	switch(cardID) {
		case 1:
			return require('../../assets/images/original_base_deck/baby_unicorn/baby_narwhal.png');
		case 2:
			return require('../../assets/images/original_base_deck/baby_unicorn/baby_unicorn_black.png');
		case 3:
			return require('../../assets/images/original_base_deck/baby_unicorn/baby_unicorn_blue.png');
		case 4:
			return require('../../assets/images/original_base_deck/baby_unicorn/baby_unicorn_brown.png');
		case 5:
			return require('../../assets/images/original_base_deck/baby_unicorn/baby_unicorn_death.png');
		case 6:
			return require('../../assets/images/original_base_deck/baby_unicorn/baby_unicorn_green.png');
		case 7:
			return require('../../assets/images/original_base_deck/baby_unicorn/baby_unicorn_orange.png');
		case 8:
			return require('../../assets/images/original_base_deck/baby_unicorn/baby_unicorn_pink.png');
		case 9:
			return require('../../assets/images/original_base_deck/baby_unicorn/baby_unicorn_purple.png');
		case 10:
			return require('../../assets/images/original_base_deck/baby_unicorn/baby_unicorn_rainbow.png');
		case 11:
			return require('../../assets/images/original_base_deck/baby_unicorn/baby_unicorn_red.png');
		case 12:
			return require('../../assets/images/original_base_deck/baby_unicorn/baby_unicorn_yellow.png');
		case 13:
			return require('../../assets/images/original_base_deck/baby_unicorn/baby_unicorn_white.png');
		case 14:
			return require('../../assets/images/original_base_deck/basic_unicorn/basic_unicorn_blue.png');
		case 15:
			return require('../../assets/images/original_base_deck/basic_unicorn/basic_unicorn_green.png');
		case 16:
			return require('../../assets/images/original_base_deck/basic_unicorn/basic_unicorn_indigo.png');
		case 17:
			return require('../../assets/images/original_base_deck/basic_unicorn/basic_unicorn_orange.png');
		case 18:
			return require('../../assets/images/original_base_deck/basic_unicorn/basic_unicorn_purple.png');
		case 19:
			return require('../../assets/images/original_base_deck/basic_unicorn/basic_unicorn_red.png');
		case 20:
			return require('../../assets/images/original_base_deck/basic_unicorn/basic_unicorn_yellow.png');
		case 21:
			return require('../../assets/images/original_base_deck/basic_unicorn/basic_narwhal.png');
		case 22:
			return require('../../assets/images/original_base_deck/magical_unicorn/alluring_narwhal.png');
		case 23:
			return require('../../assets/images/original_base_deck/magical_unicorn/americorn.png');
		case 24:
			return require('../../assets/images/original_base_deck/magical_unicorn/angel_unicorn.png');
		case 25:
			return require('../../assets/images/original_base_deck/magical_unicorn/annoying_flying_unicorn.png');
		case 26:
			return require('../../assets/images/original_base_deck/magical_unicorn/black_knight_unicorn.png');
		case 27:
			return require('../../assets/images/original_base_deck/magical_unicorn/chainsaw_unicorn.png');
		case 28:
			return require('../../assets/images/original_base_deck/magical_unicorn/classy_narwhal.png');
		case 29:
			return require('../../assets/images/original_base_deck/magical_unicorn/extremely_destructive_unicorn.png');
		case 30:
			return require('../../assets/images/original_base_deck/magical_unicorn/extremely_fertile_unicorn.png');
		case 31:
			return require('../../assets/images/original_base_deck/magical_unicorn/ginormous_unicorn.png');
		case 32:
			return require('../../assets/images/original_base_deck/magical_unicorn/greedy_flying_unicorn.png');
		case 33:
			return require('../../assets/images/original_base_deck/magical_unicorn/llamacorn.png');
		case 34:
			return require('../../assets/images/original_base_deck/magical_unicorn/magical_flying_unicorn.png');
		case 35:
			return require('../../assets/images/original_base_deck/magical_unicorn/magical_kittencorn.png');
		case 36:
			return require('../../assets/images/original_base_deck/magical_unicorn/majestic_flying_unicorn.png');
		case 37:
			return require('../../assets/images/original_base_deck/magical_unicorn/mermaid_unicorn.png');
		case 38:
			return require('../../assets/images/original_base_deck/magical_unicorn/narwhal_torpedo.png');
		case 39:
			return require('../../assets/images/original_base_deck/magical_unicorn/puppicorn.png');
		case 40:
			return require('../../assets/images/original_base_deck/magical_unicorn/queen_bee_unicorn.png');
		case 41:
			return require('../../assets/images/original_base_deck/magical_unicorn/rainbow_unicorn.png');
		case 42:
			return require('../../assets/images/original_base_deck/magical_unicorn/rhinocorn.png');
		case 43:
			return require('../../assets/images/original_base_deck/magical_unicorn/seductive_unicorn.png');
		case 44:
			return require('../../assets/images/original_base_deck/magical_unicorn/shabby_the_narwhal.png');
		case 45:
			return require('../../assets/images/original_base_deck/magical_unicorn/shark_with_a_horn.png');
		case 46:
			return require('../../assets/images/original_base_deck/magical_unicorn/stabby_the_unicorn.png');
		case 47:
			return require('../../assets/images/original_base_deck/magical_unicorn/swift_flying_unicorn.png');
		case 48:
			return require('../../assets/images/original_base_deck/magical_unicorn/the_great_narwhal.png');
		case 49:
			return require('../../assets/images/original_base_deck/magical_unicorn/unicorn_on_the_cob.png');
		case 50:
			return require('../../assets/images/original_base_deck/magical_unicorn/unicorn_phoenix.png');
		case 51:
			return require('../../assets/images/original_base_deck/magical_unicorn/zombie_unicorn.png');
		case 52:
			return require('../../assets/images/original_base_deck/magic/back_kick.png');
		case 53:
			return require('../../assets/images/original_base_deck/magic/blatant_thievery.png');
		case 54:
			return require('../../assets/images/original_base_deck/magic/change_of_luck.png');
		case 55:
			return require('../../assets/images/original_base_deck/magic/glitter_tornado.png');
		case 56:
			return require('../../assets/images/original_base_deck/magic/good_deal.png');
		case 57:
			return require('../../assets/images/original_base_deck/magic/mystical_vortex.png');
		case 58:
			return require('../../assets/images/original_base_deck/magic/re-target.png');
		case 59:
			return require('../../assets/images/original_base_deck/magic/reset_button.png');
		case 60:
			return require('../../assets/images/original_base_deck/magic/shake_up.png');
		case 61:
			return require('../../assets/images/original_base_deck/magic/targeted_destruction.png');
		case 62:
			return require('../../assets/images/original_base_deck/magic/two-for-one.png');
		case 63:
			return require('../../assets/images/original_base_deck/magic/unfair_bargain.png');
		case 64:
			return require('../../assets/images/original_base_deck/magic/unicorn_poison.png');
		case 65:
			return require('../../assets/images/original_base_deck/magic/unicorn_shrinkray.png');
		case 66:
			return require('../../assets/images/original_base_deck/magic/unicorn_swap.png');
		case 67:
			return require('../../assets/images/original_base_deck/instant/neigh.png');
		case 68:
			return require('../../assets/images/original_base_deck/instant/super_neigh.png');
		case 69:
			return require('../../assets/images/original_base_deck/upgrade/double_dutch.png');
		case 70:
			return require('../../assets/images/original_base_deck/upgrade/extra_tail.png');
		case 71:
			return require('../../assets/images/original_base_deck/upgrade/glitter_bomb.png');
		case 72:
			return require('../../assets/images/original_base_deck/upgrade/rainbow_aura.png');
		case 73:
			return require('../../assets/images/original_base_deck/upgrade/rainbow_mane.png');
		case 74:
			return require('../../assets/images/original_base_deck/upgrade/summoning_ritual.png');
		case 75:
			return require('../../assets/images/original_base_deck/upgrade/unicorn_lasso.png');
		case 76:
			return require('../../assets/images/original_base_deck/upgrade/yay.png');
		case 77:
			return require('../../assets/images/original_base_deck/downgrade/barbed_wire.png');
		case 78:
			return require('../../assets/images/original_base_deck/downgrade/blinding_light.png');
		case 79:
			return require('../../assets/images/original_base_deck/downgrade/broken_stable.png');
		case 80:
			return require('../../assets/images/original_base_deck/downgrade/nanny_cam.png');
		case 81:
			return require('../../assets/images/original_base_deck/downgrade/pandamonium.png');
		case 82:
			return require('../../assets/images/original_base_deck/downgrade/sadistic_ritual.png');
		case 83:
			return require('../../assets/images/original_base_deck/downgrade/slowdown.png');
		case 84:
			return require('../../assets/images/original_base_deck/downgrade/tiny_stable.png');
		case 85:
			return require('../../assets/images/second_edition_base_deck/magical_unicorn/mother_goose_unicorn.png');
		case 86:
			return require('../../assets/images/second_edition_base_deck/magical_unicorn/unicorn_oracle.png');
		case 87:
			return require('../../assets/images/second_edition_base_deck/magical_unicorn/necromancer_unicorn.png');
		case 88:
			return require('../../assets/images/second_edition_base_deck/magical_unicorn/dark_angel_unicorn.png');
		case 89:
			return require('../../assets/images/second_edition_base_deck/magic/kiss_of_life.png');
		case 90:
			return require('../../assets/images/second_edition_base_deck/upgrade/claw_machine.png');
		case 91:
			return require('../../assets/images/second_edition_base_deck/upgrade/stable_artillery.png');
		case 92:
			return require('../../assets/images/second_edition_base_deck/upgrade/caffeine_overload.png');
		case 93:
			return require('../../assets/images/second_edition_base_deck/upgrade/rainbow_lasso.png');
		case 94:
			return require('../../assets/images/control_base_deck/baby_unicorn/angelic_baby_unicorn.png');
		case 95:
			return require('../../assets/images/control_base_deck/baby_unicorn/baby_archangel_unicorn.png');
		case 96:
			return require('../../assets/images/control_base_deck/baby_unicorn/baby_bearicorn.png');
		case 97:
			return require('../../assets/images/control_base_deck/baby_unicorn/baby_belugacorn.png');
		case 98:
			return require('../../assets/images/control_base_deck/baby_unicorn/baby_nightmare_unicorn.png');
		case 99:
			return require('../../assets/images/control_base_deck/baby_unicorn/baby_pegasuscorn.png');
		case 100:
			return require('../../assets/images/control_base_deck/baby_unicorn/baby_penguicorn.png');
		case 101:
			return require('../../assets/images/control_base_deck/baby_unicorn/baby_slothicorn.png');
		case 102:
			return require('../../assets/images/control_base_deck/baby_unicorn/demonic_baby_unicorn.png');
		case 103:
			return require('../../assets/images/control_base_deck/baby_unicorn/million_dollar_baby_unicorn.png');
		case 104:
			return require('../../assets/images/control_base_deck/basic_unicorn/corn_on_the_cob.png');
		case 105:
			return require('../../assets/images/control_base_deck/basic_unicorn/raccoonicorn.png');
		case 106:
			return require('../../assets/images/control_base_deck/basic_unicorn/red_pandacorn.png');
		case 107:
			return require('../../assets/images/control_base_deck/basic_unicorn/suburban_dadicorn.png');
		case 108:
			return require('../../assets/images/control_base_deck/basic_unicorn/tech_supporticorn.png');
		case 109:
			return require('../../assets/images/control_base_deck/basic_unicorn/unicorn_tourist.png');
		case 110:
			return require('../../assets/images/control_base_deck/basic_unicorn/weeniecorn.png');
		case 111:
			return require('../../assets/images/control_base_deck/ultimate_unicorn/the_ancestor_unicorn.png');
		case 112:
			return require('../../assets/images/control_base_deck/ultimate_unicorn/archangel_unicorn.png');
		case 113:
			return require('../../assets/images/control_base_deck/ultimate_unicorn/chronocorn.png');
		case 114:
			return require('../../assets/images/control_base_deck/ultimate_unicorn/elusive_oceloticorn.png');
		case 115:
			return require('../../assets/images/control_base_deck/ultimate_unicorn/game_master_unicorn.png');
		case 116:
			return require('../../assets/images/control_base_deck/ultimate_unicorn/nine_tailed_foxicorn.png');
		case 117:
			return require('../../assets/images/control_base_deck/ultimate_unicorn/the_rad_scientist_unicorn.png');
		case 118:
			return require('../../assets/images/control_base_deck/ultimate_unicorn/time_shifting_unicorn.png');
		case 119:
			return require('../../assets/images/control_base_deck/ultimate_unicorn/unicorn_of_conniving_artistry.png');
		case 120:
			return require('../../assets/images/control_base_deck/ultimate_unicorn/unicorn_of_glory.png');
		case 121:
			return require('../../assets/images/control_base_deck/magical_unicorn/academicorn.png');
		case 122:
			return require('../../assets/images/control_base_deck/magical_unicorn/alchemist_unicorn.png');
		case 123:
			return require('../../assets/images/control_base_deck/magical_unicorn/dingocorn.png');
		case 124:
			return require('../../assets/images/control_base_deck/magical_unicorn/dread_pirate_unicorn.png');
		case 125:
			return require('../../assets/images/control_base_deck/magical_unicorn/excited_sealicorn.png');
		case 126:
			return require('../../assets/images/control_base_deck/magical_unicorn/fortune_teller_unicorn.png');
		case 127:
			return require('../../assets/images/control_base_deck/magical_unicorn/foxicorn.png');
		case 128:
			return require('../../assets/images/control_base_deck/magical_unicorn/golden_retrievercorn.png');
		case 129:
			return require('../../assets/images/control_base_deck/magical_unicorn/hypnocorn.png');
		case 130:
			return require('../../assets/images/control_base_deck/magical_unicorn/lady_justice_unicorn.png');
		case 131:
			return require('../../assets/images/control_base_deck/magical_unicorn/mama_unicorn.png');
		case 132:
			return require('../../assets/images/control_base_deck/magical_unicorn/mutually_assured_destructicorn.png');
		case 133:
			return require('../../assets/images/control_base_deck/magical_unicorn/nannycorn.png');
		case 134:
			return require('../../assets/images/control_base_deck/magical_unicorn/nymphicorn.png');
		case 135:
			return require('../../assets/images/control_base_deck/magical_unicorn/parallel_universicorn.png');
		case 136:
			return require('../../assets/images/control_base_deck/magical_unicorn/patient_zero_unicorn.png');
		case 137:
			return require('../../assets/images/control_base_deck/magical_unicorn/pickpocket_unicorn.png');
		case 138:
			return require('../../assets/images/control_base_deck/magical_unicorn/pied_pipercorn.png');
		case 139:
			return require('../../assets/images/control_base_deck/magical_unicorn/regifting_unicorn.png');
		case 140:
			return require('../../assets/images/control_base_deck/magical_unicorn/sacrificial_lambicorn.png');
		case 141:
			return require('../../assets/images/control_base_deck/magical_unicorn/slothicorn.png');
		case 142:
			return require('../../assets/images/control_base_deck/magical_unicorn/spy_unicorn.png');
		case 143:
			return require('../../assets/images/control_base_deck/magical_unicorn/traffic_director_unicorn.png');
		case 144:
			return require('../../assets/images/control_base_deck/magical_unicorn/trojan_unicorn.png');
		case 145:
			return require('../../assets/images/control_base_deck/magical_unicorn/twin_unicorns.png');
		case 146:
			return require('../../assets/images/control_base_deck/magical_unicorn/unicorn_of_charity.png');
		case 147:
			return require('../../assets/images/control_base_deck/magical_unicorn/unicorn_prophet.png');
		case 148:
			return require('../../assets/images/control_base_deck/magical_unicorn/unicorn_trap_master.png');
		case 149:
			return require('../../assets/images/control_base_deck/magical_unicorn/wrecking_ball_unicorn.png');
		case 150:
			return require('../../assets/images/control_base_deck/magic/archangels_blessing.png');
		case 151:
			return require('../../assets/images/control_base_deck/magic/controlled_destruction.png');
		case 152:
			return require('../../assets/images/control_base_deck/magic/grow_up.png');
		case 153:
			return require('../../assets/images/control_base_deck/magic/merry_go_round.png');
		case 154:
			return require('../../assets/images/control_base_deck/magic/prospecting.png');
		case 155:
			return require('../../assets/images/control_base_deck/magic/quid_pro_quo.png');
		case 156:
			return require('../../assets/images/control_base_deck/magic/rainbow_bazooka.png');
		case 157:
			return require('../../assets/images/control_base_deck/magic/rainbow_bridge.png');
		case 158:
			return require('../../assets/images/control_base_deck/magic/spring_cleaning.png');
		case 159:
			return require('../../assets/images/control_base_deck/magic/temporal_paradox.png');
		case 160:
			return require('../../assets/images/control_base_deck/magic/time_rift.png');
		case 161:
			return require('../../assets/images/control_base_deck/magic/totally_not_two_unicorns.png');
		case 162:
			return require('../../assets/images/control_base_deck/magic/unicorn_black_market.png');
		case 163:
			return require('../../assets/images/control_base_deck/magic/unicorn_trap.png');
		case 164:
			return require('../../assets/images/control_base_deck/magic/unicorns_forever.png');
		case 165:
			return require('../../assets/images/control_base_deck/magic/unicornucopia.png');
		case 166:
			return require('../../assets/images/control_base_deck/magic/wishing_well.png');
		case 167:
			return require('../../assets/images/control_base_deck/magic/yoink.png');
		case 168:
			return require('../../assets/images/control_base_deck/instant/bulletproof_vest.png');
		case 169:
			return require('../../assets/images/control_base_deck/instant/destabilize.png');
		case 170:
			return require('../../assets/images/control_base_deck/instant/imitation.png');
		case 171:
			return require('../../assets/images/control_base_deck/instant/neigh_angel.png');
		case 172:
			return require('../../assets/images/control_base_deck/instant/neigh_demon.png');
		case 173:
			return require('../../assets/images/control_base_deck/instant/super_neigh_cec.png');
		case 174:
			return require('../../assets/images/control_base_deck/instant/unwind_and_rewind.png');
		case 175:
			return require('../../assets/images/control_base_deck/upgrade/controlled_chaos.png');
		case 176:
			return require('../../assets/images/control_base_deck/upgrade/extra_life.png');
		case 177:
			return require('../../assets/images/control_base_deck/upgrade/foresight.png');
		case 178:
			return require('../../assets/images/control_base_deck/upgrade/glass_half_full.png');
		case 179:
			return require('../../assets/images/control_base_deck/upgrade/imaginary_friendicorn.png');
		case 180:
			return require('../../assets/images/control_base_deck/upgrade/objection.png');
		case 181:
			return require('../../assets/images/control_base_deck/upgrade/retribution.png');
		case 182:
			return require('../../assets/images/control_base_deck/upgrade/unicorn_adoption_agency.png');
		case 183:
			return require('../../assets/images/control_base_deck/upgrade/unicorn_bribe.png');
		case 184:
			return require('../../assets/images/control_base_deck/upgrade/unicorn_mafia.png');
		case 185:
			return require('../../assets/images/control_base_deck/downgrade/anti_magic_bubble.png');
		case 186:
			return require('../../assets/images/control_base_deck/downgrade/black_hole.png');
		case 187:
			return require('../../assets/images/control_base_deck/downgrade/brain_freeze.png');
		case 188:
			return require('../../assets/images/control_base_deck/downgrade/catastrophe.png');
		case 189:
			return require('../../assets/images/control_base_deck/downgrade/greener_pastures.png');
		case 190:
			return require('../../assets/images/control_base_deck/downgrade/otter_devastation.png');
		case 191:
			return require('../../assets/images/control_base_deck/downgrade/restricted_area.png');
		case 192:
			return require('../../assets/images/control_base_deck/downgrade/unicorn_abduction.png');
		case 193:
			return require('../../assets/images/control_base_deck/downgrade/unicorn_tax.png');
		default:
			return require('../../assets/images/unicorn_not_found.png');
	}
}