export default function getCardImage(cardID) {
	switch(cardID) {
		case 1:
			return require('../../assets/images/original_base_deck/baby_unicorn/baby_narwhal.png');
		case 2:
			return require('../../assets/images/original_base_deck/baby_unicorn/baby_unicorn_black.png');
		case 3:
			return require('../../assets/images/original_base_deck/baby_unicorn/baby_unicorn_blue.png');
		case 4:
			return require('../../assets/images/original_base_deck/baby_unicorn/baby_unicorn_brown.png');
		case 5:
			return require('../../assets/images/original_base_deck/baby_unicorn/baby_unicorn_death.png');
		case 6:
			return require('../../assets/images/original_base_deck/baby_unicorn/baby_unicorn_green.png');
		case 7:
			return require('../../assets/images/original_base_deck/baby_unicorn/baby_unicorn_orange.png');
		case 8:
			return require('../../assets/images/original_base_deck/baby_unicorn/baby_unicorn_pink.png');
		case 9:
			return require('../../assets/images/original_base_deck/baby_unicorn/baby_unicorn_purple.png');
		case 10:
			return require('../../assets/images/original_base_deck/baby_unicorn/baby_unicorn_rainbow.png');
		case 11:
			return require('../../assets/images/original_base_deck/baby_unicorn/baby_unicorn_red.png');
		case 12:
			return require('../../assets/images/original_base_deck/baby_unicorn/baby_unicorn_yellow.png');
		case 13:
			return require('../../assets/images/original_base_deck/baby_unicorn/baby_unicorn_white.png');
		case 14:
			return require('../../assets/images/original_base_deck/basic_unicorn/basic_unicorn_blue.png');
		case 15:
			return require('../../assets/images/original_base_deck/basic_unicorn/basic_unicorn_green.png');
		case 16:
			return require('../../assets/images/original_base_deck/basic_unicorn/basic_unicorn_indigo.png');
		case 17:
			return require('../../assets/images/original_base_deck/basic_unicorn/basic_unicorn_orange.png');
		case 18:
			return require('../../assets/images/original_base_deck/basic_unicorn/basic_unicorn_purple.png');
		case 19:
			return require('../../assets/images/original_base_deck/basic_unicorn/basic_unicorn_red.png');
		case 20:
			return require('../../assets/images/original_base_deck/basic_unicorn/basic_unicorn_yellow.png');
		case 21:
			return require('../../assets/images/original_base_deck/basic_unicorn/basic_narwhal.png');
		case 22:
			return require('../../assets/images/original_base_deck/magical_unicorn/alluring_narwhal.png');
		case 23:
			return require('../../assets/images/original_base_deck/magical_unicorn/americorn.png');
		case 24:
			return require('../../assets/images/original_base_deck/magical_unicorn/angel_unicorn.png');
		case 25:
			return require('../../assets/images/original_base_deck/magical_unicorn/annoying_flying_unicorn.png');
		case 26:
			return require('../../assets/images/original_base_deck/magical_unicorn/black_knight_unicorn.png');
		case 27:
			return require('../../assets/images/original_base_deck/magical_unicorn/chainsaw_unicorn.png');
		case 28:
			return require('../../assets/images/original_base_deck/magical_unicorn/classy_narwhal.png');
		case 29:
			return require('../../assets/images/original_base_deck/magical_unicorn/extremely_destructive_unicorn.png');
		case 30:
			return require('../../assets/images/original_base_deck/magical_unicorn/extremely_fertile_unicorn.png');
		case 31:
			return require('../../assets/images/original_base_deck/magical_unicorn/ginormous_unicorn.png');
		case 32:
			return require('../../assets/images/original_base_deck/magical_unicorn/greedy_flying_unicorn.png');
		case 33:
			return require('../../assets/images/original_base_deck/magical_unicorn/llamacorn.png');
		case 34:
			return require('../../assets/images/original_base_deck/magical_unicorn/magical_flying_unicorn.png');
		case 35:
			return require('../../assets/images/original_base_deck/magical_unicorn/magical_kittencorn.png');
		case 36:
			return require('../../assets/images/original_base_deck/magical_unicorn/majestic_flying_unicorn.png');
		case 37:
			return require('../../assets/images/original_base_deck/magical_unicorn/mermaid_unicorn.png');
		case 38:
			return require('../../assets/images/original_base_deck/magical_unicorn/narwhal_torpedo.png');
		case 39:
			return require('../../assets/images/original_base_deck/magical_unicorn/puppicorn.png');
		case 40:
			return require('../../assets/images/original_base_deck/magical_unicorn/queen_bee_unicorn.png');
		case 41:
			return require('../../assets/images/original_base_deck/magical_unicorn/rainbow_unicorn.png');
		case 42:
			return require('../../assets/images/original_base_deck/magical_unicorn/rhinocorn.png');
		case 43:
			return require('../../assets/images/original_base_deck/magical_unicorn/seductive_unicorn.png');
		case 44:
			return require('../../assets/images/original_base_deck/magical_unicorn/shabby_the_narwhal.png');
		case 45:
			return require('../../assets/images/original_base_deck/magical_unicorn/shark_with_a_horn.png');
		case 46:
			return require('../../assets/images/original_base_deck/magical_unicorn/stabby_the_unicorn.png');
		case 47:
			return require('../../assets/images/original_base_deck/magical_unicorn/swift_flying_unicorn.png');
		case 48:
			return require('../../assets/images/original_base_deck/magical_unicorn/the_great_narwhal.png');
		case 49:
			return require('../../assets/images/original_base_deck/magical_unicorn/unicorn_on_the_cob.png');
		case 50:
			return require('../../assets/images/original_base_deck/magical_unicorn/unicorn_phoenix.png');
		case 51:
			return require('../../assets/images/original_base_deck/magical_unicorn/zombie_unicorn.png');
		case 52:
			return require('../../assets/images/original_base_deck/magic/back_kick.png');
		case 53:
			return require('../../assets/images/original_base_deck/magic/blatant_thievery.png');
		case 54:
			return require('../../assets/images/original_base_deck/magic/change_of_luck.png');
		case 55:
			return require('../../assets/images/original_base_deck/magic/glitter_tornado.png');
		case 56:
			return require('../../assets/images/original_base_deck/magic/good_deal.png');
		case 57:
			return require('../../assets/images/original_base_deck/magic/mystical_vortex.png');
		case 58:
			return require('../../assets/images/original_base_deck/magic/re-target.png');
		case 59:
			return require('../../assets/images/original_base_deck/magic/reset_button.png');
		case 60:
			return require('../../assets/images/original_base_deck/magic/shake_up.png');
		case 61:
			return require('../../assets/images/original_base_deck/magic/targeted_destruction.png');
		case 62:
			return require('../../assets/images/original_base_deck/magic/two-for-one.png');
		case 63:
			return require('../../assets/images/original_base_deck/magic/unfair_bargain.png');
		case 64:
			return require('../../assets/images/original_base_deck/magic/unicorn_poison.png');
		case 65:
			return require('../../assets/images/original_base_deck/magic/unicorn_shrinkray.png');
		case 66:
			return require('../../assets/images/original_base_deck/magic/unicorn_swap.png');
		case 67:
			return require('../../assets/images/original_base_deck/instant/neigh.png');
		case 68:
			return require('../../assets/images/original_base_deck/instant/super_neigh.png');
		case 69:
			return require('../../assets/images/original_base_deck/upgrade/double_dutch.png');
		case 70:
			return require('../../assets/images/original_base_deck/upgrade/extra_tail.png');
		case 71:
			return require('../../assets/images/original_base_deck/upgrade/glitter_bomb.png');
		case 72:
			return require('../../assets/images/original_base_deck/upgrade/rainbow_aura.png');
		case 73:
			return require('../../assets/images/original_base_deck/upgrade/rainbow_mane.png');
		case 74:
			return require('../../assets/images/original_base_deck/upgrade/summoning_ritual.png');
		case 75:
			return require('../../assets/images/original_base_deck/upgrade/unicorn_lasso.png');
		case 76:
			return require('../../assets/images/original_base_deck/upgrade/yay.png');
		case 77:
			return require('../../assets/images/original_base_deck/downgrade/barbed_wire.png');
		case 78:
			return require('../../assets/images/original_base_deck/downgrade/blinding_light.png');
		case 79:
			return require('../../assets/images/original_base_deck/downgrade/broken_stable.png');
		case 80:
			return require('../../assets/images/original_base_deck/downgrade/nanny_cam.png');
		case 81:
			return require('../../assets/images/original_base_deck/downgrade/pandamonium.png');
		case 82:
			return require('../../assets/images/original_base_deck/downgrade/sadistic_ritual.png');
		case 83:
			return require('../../assets/images/original_base_deck/downgrade/slowdown.png');
		case 84:
			return require('../../assets/images/original_base_deck/downgrade/tiny_stable.png');
		case 85:
			return require('../../assets/images/second_edition_base_deck/magical_unicorn/mother_goose_unicorn.png');
		case 86:
			return require('../../assets/images/second_edition_base_deck/magical_unicorn/unicorn_oracle.png');
		case 87:
			return require('../../assets/images/second_edition_base_deck/magical_unicorn/necromancer_unicorn.png');
		case 88:
			return require('../../assets/images/second_edition_base_deck/magical_unicorn/dark_angel_unicorn.png');
		case 89:
			return require('../../assets/images/second_edition_base_deck/magic/kiss_of_life.png');
		case 90:
			return require('../../assets/images/second_edition_base_deck/upgrade/claw_machine.png');
		case 91:
			return require('../../assets/images/second_edition_base_deck/upgrade/stable_artillery.png');
		case 92:
			return require('../../assets/images/second_edition_base_deck/upgrade/caffeine_overload.png');
		case 93:
			return require('../../assets/images/second_edition_base_deck/upgrade/rainbow_lasso.png');
		default:
			return require('../../assets/images/unicorn_not_found.png');
	}
}